using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PCK.Model;
using PCK.Web.ViewModels;

namespace PCK.Web.Controllers
{
    public class SalesController : Controller
    {
        private readonly SalesContext _context;

        public SalesController(SalesContext context)
        {
            _context = context;
        }

        [HttpPost]
        public JsonResult Save([FromBody]SalesOrderViewModel salesOrderViewModel)
        {
            //significant variance from how MVC4 processed ajax requests
            //https://stackoverflow.com/questions/47540406/model-binding-in-mvc-core-from-knockoutjs
            if (ModelState.IsValid)
            {
                var salesOrder = new SalesOrder();
                salesOrder.CustomerName = salesOrderViewModel.CustomerName;
                salesOrder.PONumber = salesOrderViewModel.PONumber;
                _context.SalesOrder.Add(salesOrder);
                _context.SaveChanges();

                salesOrderViewModel.MessageToClient = string.Format("{0}'s order was saved.", salesOrder.CustomerName);


                return Json(JsonConvert.SerializeObject(salesOrderViewModel));
            }
            else
            {
                return Json(JsonConvert.SerializeObject(ModelState));
            }
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.SalesOrder.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salesOrder = await _context.SalesOrder
                .SingleOrDefaultAsync(m => m.SalesOrderId == id);
            if (salesOrder == null)
            {
                return NotFound();
            }
            SalesOrderViewModel viewModel = new SalesOrderViewModel
            {
                PONumber = salesOrder.PONumber,
                CustomerName = salesOrder.CustomerName,
                SalesOrderId = salesOrder.SalesOrderId,
                MessageToClient = "This msg generated by the ViewModel!"
            };

            return View(viewModel);
        }

        public IActionResult Create()
        {

            SalesOrderViewModel viewModel = new SalesOrderViewModel();
            return View(viewModel);
        }

        //// POST: Sales/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("SalesOrderId,CustomerName,PONumber")] SalesOrder salesOrder)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(salesOrder);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(salesOrder);
        //}

        // GET: Sales/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salesOrder = await _context.SalesOrder.SingleOrDefaultAsync(m => m.SalesOrderId == id);
            if (salesOrder == null)
            {
                return NotFound();
            }
            return View(salesOrder);
        }

        // POST: Sales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SalesOrderId,CustomerName,PONumber")] SalesOrder salesOrder)
        {
            if (id != salesOrder.SalesOrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(salesOrder);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalesOrderExists(salesOrder.SalesOrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(salesOrder);
        }

        // GET: Sales/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salesOrder = await _context.SalesOrder
                .SingleOrDefaultAsync(m => m.SalesOrderId == id);
            if (salesOrder == null)
            {
                return NotFound();
            }

            return View(salesOrder);
        }

        // POST: Sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var salesOrder = await _context.SalesOrder.SingleOrDefaultAsync(m => m.SalesOrderId == id);
            _context.SalesOrder.Remove(salesOrder);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalesOrderExists(int id)
        {
            return _context.SalesOrder.Any(e => e.SalesOrderId == id);
        }
    }
}
